In [2]:
import random
import numpy as np
import pandas as pd

In [23]:
df=pd.read_csv('hw2dataNorm.csv')
df=df.iloc[:,1:]
data=df.to_numpy()
# class values
y=data[:,-1]
X=data[:,:-1]
stepSize=0.01

w0=np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
w=np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
def sigmoidLikelihood(X,y,w):
   
    n,m=X.shape
        
    tem=np.ones((n,1))
    
    X=np.append(X,tem,1)
    g =np.array( 1 / (1 +np.exp( - (X.dot(w) ) )))
    
    pred=[]
    for i in range(0,len(X)): 
        ML= ((1-g[i])**(1-y[i]))*((g[i])**y[i])    
        # pred.append(ML)
        
    return np.array(g)
    

In [30]:
LVector = sigmoidLikelihood(X, y, w)
LVector[1]

array([0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5])

# Q2
# a) 249
# b)-5991.464547107981

a) If LVector contains all values of 0.05 ([0.05, 0.05, 0.05, ..., 0.05]), how many data points (elements in LVector) are needed for np.prod to estimate the pseudo-likelihood as perfectly 0?

In [14]:
x=np.full((2000),0.05)
def  count(value):
    count=0
    for i in range(len(x)):
        pro=value**i

        if pro==0:
            print(count)
            break
        count+=1
count(0.05)

249


b) What is the pseudo-log-likelihood equivalent given the number of data points from part (a)?

In [15]:
n,m=X.shape
x=np.full((249),0.05)
np.sum(np.log(x))

-745.9373361149437

In [433]:
# np.prod(x)

0.0

# Q3

In [34]:
def learnLogistic(w0,X, y,K):

    n,m=X.shape
    #creating a n rows of 1 to accomodate b
    
    tem=np.ones((n,1))

    X1=np.append(X,tem,1)
    
   
    
    count=0
    log_Lvector=[]
    
    w1=np.copy(w0)
    
    prob =np.array( 1 / (1 +np.exp( - (X1.dot(w1) ) )))
    
    
    while count!=K:
        update=np.zeros(m+1)
        
        for i,datapt in enumerate(X1):
            for j,feature in enumerate(datapt):
                update[j] += stepSize *(X1[i,j])*( y[i]-prob[i])

        for index,i in enumerate(update):
            w1[index] += update[index]
        

        count+=1
        Lvector=sigmoidLikelihood(X,y,w1)
        log_Lvector.append(np.sum(np.log(Lvector)))
   
        
    return np.array(w1),np.array(log_Lvector)

In [36]:
K=10
w,LHistory=learnLogistic(w0,X,y,K)
LHistory

array([ -6209.84367925, -12203.04638477, -18243.73271559, -24296.55201075,
       -30354.25616771, -36414.38707039, -42475.89097829, -48538.24577992,
       -54601.16453999, -60664.4766324 ])

# Q4

In [37]:
def learnLogisticFast(w0,X,y,K):
     
    n,m=X.shape
   
    
    tem=np.ones((n,1))
    
    X1=np.append(X,tem,1)
   
    
    dataPt=X1

    
    count=0
    log_Lvector=[]
    w1=np.copy(w0)
    
    prob =np.array( 1 / (1 +np.exp( - (dataPt.dot(w1) ) )))
    
    while count!=K:
        update=np.zeros(m+1)
    
        for i in range(len(X1)):

             update+= stepSize *(X1[i,:])*( y[i]-prob[i])

        for index,i in enumerate(update):
            w1[index] += update[index]

        count+=1
        Lvector=sigmoidLikelihood(X,y,w1)
        log_Lvector.append(np.sum(np.log(Lvector)))
        
    return np.array(w1),np.array(log_Lvector)

In [38]:
K=10
w,LHistory=learnLogisticFast(w0,X,y,K)
LHistory

array([ -6209.84367925, -12203.04638477, -18243.73271559, -24296.55201075,
       -30354.25616771, -36414.38707039, -42475.89097829, -48538.24577992,
       -54601.16453999, -60664.4766324 ])

# Part b
K=10
# learnLogistic(w0,X,y,K) = 0.46728801727294920
# learnLogisticFast(w0,X,y,K)=0.2627539634704590

In [42]:
df=pd.read_csv('hw2dataNorm.csv')
df=df.iloc[:,1:]
data=df.to_numpy()
# class values
y=data[:,-1]
X=data[:,:-1]
w0=np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
import time
timeStart=time.time()
K=10
w,LHistory=learnLogistic(w0,X,y,K)
timeEnd=time.time()
print(timeEnd-timeStart)


0.4672880172729492


In [43]:

import time
timeStart=time.time()
K=10

w0=np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
w,LHistory=learnLogisticFast(w0,X,y,K)
timeEnd=time.time()
print(timeEnd-timeStart)


0.262753963470459


# Q5

In [89]:
# df=pd.read_csv('hw2dataNorm.csv')
# df=df.iloc[:,1:]
# data=df.to_numpy()
# y=data[:,-1]
# x=data[:,:-1]
# w=np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [90]:
def logisticClassify(x,w):
   

    n,m=x.shape

    tem=np.ones((n,1))
    
    x=np.append(x,tem,1)
    
    Y_pred =np.array( 1 / (1 +np.exp( - (x.dot(w) ) )))
    
    Y_pred = np.where( Y_pred < 0.5,0,1)
    # this is pseudo-code!
    return np.array(Y_pred)

In [91]:
classLabels=logisticClassify(x,w)